/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuillaiInfoRouteImport } from './routes/quillai-info'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as R3dKreaturenRouteImport } from './routes/3d-kreaturen'
import { Route as R3dKreatorRouteImport } from './routes/3d-kreator'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiPublicPaypalWebhookRouteImport } from './routes/api/public/paypal-webhook'
import { Route as ApiPublicNowpaymentsWebhookRouteImport } from './routes/api/public/nowpayments-webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuillaiInfoRoute = QuillaiInfoRouteImport.update({
  id: '/quillai-info',
  path: '/quillai-info',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dKreaturenRoute = R3dKreaturenRouteImport.update({
  id: '/3d-kreaturen',
  path: '/3d-kreaturen',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dKreatorRoute = R3dKreatorRouteImport.update({
  id: '/3d-kreator',
  path: '/3d-kreator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaypalWebhookRoute = ApiPublicPaypalWebhookRouteImport.update({
  id: '/api/public/paypal-webhook',
  path: '/api/public/paypal-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNowpaymentsWebhookRoute =
  ApiPublicNowpaymentsWebhookRouteImport.update({
    id: '/api/public/nowpayments-webhook',
    path: '/api/public/nowpayments-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3d-kreator': typeof R3dKreatorRoute
  '/3d-kreaturen': typeof R3dKreaturenRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/quillai-info': typeof QuillaiInfoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/nowpayments-webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3d-kreator': typeof R3dKreatorRoute
  '/3d-kreaturen': typeof R3dKreaturenRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/quillai-info': typeof QuillaiInfoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/nowpayments-webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/3d-kreator': typeof R3dKreatorRoute
  '/3d-kreaturen': typeof R3dKreaturenRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/quillai-info': typeof QuillaiInfoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/public/nowpayments-webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/3d-kreator'
    | '/3d-kreaturen'
    | '/ai-chat'
    | '/auth'
    | '/privacy'
    | '/quillai-info'
    | '/reset-password'
    | '/safety'
    | '/sitemap.xml'
    | '/terms'
    | '/settings'
    | '/api/public/nowpayments-webhook'
    | '/api/public/paypal-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/3d-kreator'
    | '/3d-kreaturen'
    | '/ai-chat'
    | '/auth'
    | '/privacy'
    | '/quillai-info'
    | '/reset-password'
    | '/safety'
    | '/sitemap.xml'
    | '/terms'
    | '/settings'
    | '/api/public/nowpayments-webhook'
    | '/api/public/paypal-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/3d-kreator'
    | '/3d-kreaturen'
    | '/ai-chat'
    | '/auth'
    | '/privacy'
    | '/quillai-info'
    | '/reset-password'
    | '/safety'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/settings'
    | '/api/public/nowpayments-webhook'
    | '/api/public/paypal-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R3dKreatorRoute: typeof R3dKreatorRoute
  R3dKreaturenRoute: typeof R3dKreaturenRoute
  AiChatRoute: typeof AiChatRoute
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  QuillaiInfoRoute: typeof QuillaiInfoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SafetyRoute: typeof SafetyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPublicNowpaymentsWebhookRoute: typeof ApiPublicNowpaymentsWebhookRoute
  ApiPublicPaypalWebhookRoute: typeof ApiPublicPaypalWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quillai-info': {
      id: '/quillai-info'
      path: '/quillai-info'
      fullPath: '/quillai-info'
      preLoaderRoute: typeof QuillaiInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d-kreaturen': {
      id: '/3d-kreaturen'
      path: '/3d-kreaturen'
      fullPath: '/3d-kreaturen'
      preLoaderRoute: typeof R3dKreaturenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d-kreator': {
      id: '/3d-kreator'
      path: '/3d-kreator'
      fullPath: '/3d-kreator'
      preLoaderRoute: typeof R3dKreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/paypal-webhook': {
      id: '/api/public/paypal-webhook'
      path: '/api/public/paypal-webhook'
      fullPath: '/api/public/paypal-webhook'
      preLoaderRoute: typeof ApiPublicPaypalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nowpayments-webhook': {
      id: '/api/public/nowpayments-webhook'
      path: '/api/public/nowpayments-webhook'
      fullPath: '/api/public/nowpayments-webhook'
      preLoaderRoute: typeof ApiPublicNowpaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R3dKreatorRoute: R3dKreatorRoute,
  R3dKreaturenRoute: R3dKreaturenRoute,
  AiChatRoute: AiChatRoute,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  QuillaiInfoRoute: QuillaiInfoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SafetyRoute: SafetyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPublicNowpaymentsWebhookRoute: ApiPublicNowpaymentsWebhookRoute,
  ApiPublicPaypalWebhookRoute: ApiPublicPaypalWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
