DROP TABLE IF EXISTS public.chat_reports CASCADE;
DROP TABLE IF EXISTS public.user_strikes CASCADE;
DROP TABLE IF EXISTS public.conversation_clears CASCADE;
DROP TABLE IF EXISTS public.messages CASCADE;
DROP TABLE IF EXISTS public.conversations CASCADE;
DROP TABLE IF EXISTS public.blocked_users CASCADE;
DROP TABLE IF EXISTS public.saved_posts CASCADE;
DROP TABLE IF EXISTS public.thumbs_up CASCADE;
DROP TABLE IF EXISTS public.likes CASCADE;
DROP TABLE IF EXISTS public.comments CASCADE;
DROP TABLE IF EXISTS public.follows CASCADE;
DROP TABLE IF EXISTS public.posts CASCADE;
DROP FUNCTION IF EXISTS public.create_post_comment(uuid, text) CASCADE;
DROP FUNCTION IF EXISTS public.get_or_create_conversation(uuid) CASCADE;
DROP FUNCTION IF EXISTS public.is_blocked_between(uuid, uuid) CASCADE;
DROP FUNCTION IF EXISTS public.remove_heart_on_thumbs() CASCADE;
DROP FUNCTION IF EXISTS public.remove_thumbs_on_heart() CASCADE;
DROP FUNCTION IF EXISTS public.bump_conversation_last_message() CASCADE;
DROP FUNCTION IF EXISTS public.get_post_comments(uuid) CASCADE;